BUGFIX. Gets error deploying to gh-pages
Error:
- setup-node@v1.1.0 is deprecated and setup-node@v2 should be used
Error: Unable to process command '##[add-path]/opt/hostedtoolcache/node/12.22.9/x64/bin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://github.com/beatrizsmerino/vue-editor/runs/4804870987?check_suite_focus=true
- The npm script 'gh-pages-deploy' does not exist

Solution:
- https://github.com/Rolanddoda/vue-cli-plugin-gh-pages-auto-deploy/blob/master/generator/templates/_github/workflows/gh-pages-deploy.yml
- Change the name of the npm script 'gh-pages-deploy' to 'deploy'